/usr/local/mysql/bin/mysql -uroot -p

DROP DATABASE TODOS;
CREATE DATABASE TODOS;
USE TODOS;

CREATE TABLE TODO ( 
ID INT AUTO_INCREMENT, 
TITLE VARCHAR(50) NOT NULL, 
DESCRIPTION VARCHAR(50), 
CREATED_DT DATE, 
PRIMARY KEY(ID));