/usr/local/mysql/bin/mysql -uroot -p

USE TODOS;
DROP DATABASE TODOS;
CREATE DATABASE TODOS;
USE TODOS;

CREATE TABLE TODO_CATEGORY (
    ID INT AUTO_INCREMENT,
    CATEGORY VARCHAR(40) NOT NULL,
    PRIMARY KEY(ID));

CREATE TABLE TODO (
    ID INT AUTO_INCREMENT, 
    CATEGORY_ID INT NOT NULL, 
    TITLE VARCHAR(50) NOT NULL, 
    DESCRIPTION VARCHAR(50), 
    CREATED_DT DATE,
    PRIMARY KEY(ID), 
    CONSTRAINT FK_CategoryTodo FOREIGN KEY (CATEGORY_ID)
    REFERENCES TODO_CATEGORY(ID));
